import type { AuthUser } from '@/features/auth/api';
import type { BudgetSummary } from '@/features/budget/api';
import type { Task } from '@/features/tasks/api';
import type { Vendor } from '@/features/vendors/api';
import type { Member, Wedding, WeddingRole } from '@/features/weddings/api';

/**
 * Everything the public demo shows — one fictional couple, entirely made
 * up. This is the whole "backend" for the demo build: no server, no
 * database, just this module bundled into the static site (see
 * lib/mockApi.ts, which serves it in place of real fetch() calls when
 * lib/demo.ts's DEMO_MODE is true).
 *
 * Dates are computed relative to "now" rather than hardcoded, so the demo
 * never looks stale — a countdown that would've read "-40 days to go" two
 * months after this was written, or a task list where every "overdue" item
 * actually isn't anymore.
 */

function daysFromNow(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

export const DEMO_USER: AuthUser = {
  id: 'demo-user',
  email: 'demo@everafter.app',
  fullName: 'Demo Viewer',
};

export const DEMO_WEDDING_ID = 'demo-wedding';
export const DEMO_ROLE: WeddingRole = 'viewer';

export const DEMO_WEDDING: Wedding = {
  id: DEMO_WEDDING_ID,
  name: 'Priya & Sam',
  weddingDate: daysFromNow(243),
  currency: 'USD',
  totalBudget: '42000',
  createdAt: '2026-01-05T00:00:00.000Z',
};

export const DEMO_MEMBERS: Member[] = [
  {
    id: 'demo-member',
    userId: DEMO_USER.id,
    fullName: DEMO_USER.fullName,
    email: DEMO_USER.email,
    role: DEMO_ROLE,
    status: 'active',
  },
];

// budgetCategoryId values below are made up to match — there's no real
// budget_categories table in the demo, just these ids referenced
// consistently between DEMO_BUDGET_SUMMARY.categories and each vendor.
const CATEGORY = {
  venue: 'cat-venue',
  catering: 'cat-catering',
  photography: 'cat-photography',
  videography: 'cat-videography',
  florist: 'cat-florist',
  music: 'cat-music',
  beauty: 'cat-beauty',
  rentals: 'cat-rentals',
} as const;

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'vendor-willowmere',
    weddingId: DEMO_WEDDING_ID,
    name: 'Willowmere Estate',
    category: 'venue',
    status: 'booked',
    budgetCategoryId: CATEGORY.venue,
    contactName: 'Dana Whitfield',
    email: null,
    phone: null,
    website: null,
    estimatedCost: '14200',
    notes: 'Garden ceremony + indoor reception, rain plan included.',
    createdAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: 'vendor-cedar-hollow',
    weddingId: DEMO_WEDDING_ID,
    name: 'Cedar Hollow Barn',
    category: 'venue',
    status: 'declined',
    budgetCategoryId: CATEGORY.venue,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '11000',
    notes: 'Beautiful, but no on-site parking.',
    createdAt: '2026-01-20T00:00:00.000Z',
  },
  {
    id: 'vendor-maple-stone',
    weddingId: DEMO_WEDDING_ID,
    name: 'Maple & Stone Hall',
    category: 'venue',
    status: 'declined',
    budgetCategoryId: CATEGORY.venue,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '16500',
    notes: null,
    createdAt: '2026-01-18T00:00:00.000Z',
  },
  {
    id: 'vendor-saffron',
    weddingId: DEMO_WEDDING_ID,
    name: 'Saffron Table Catering',
    category: 'catering',
    status: 'booked',
    budgetCategoryId: CATEGORY.catering,
    contactName: 'Marcus Ihejirika',
    email: null,
    phone: null,
    website: null,
    estimatedCost: '7600',
    notes: 'Plated dinner, 110 guests, one vegetarian + one gluten-free option.',
    createdAt: '2026-02-15T00:00:00.000Z',
  },
  {
    id: 'vendor-harborline',
    weddingId: DEMO_WEDDING_ID,
    name: 'Harborline Events Catering',
    category: 'catering',
    status: 'quote_received',
    budgetCategoryId: CATEGORY.catering,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '8400',
    notes: null,
    createdAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: 'vendor-amber-oak',
    weddingId: DEMO_WEDDING_ID,
    name: 'Amber & Oak Photography',
    category: 'photography',
    status: 'booked',
    budgetCategoryId: CATEGORY.photography,
    contactName: 'Lena Ferraro',
    email: null,
    phone: null,
    website: null,
    estimatedCost: '4300',
    notes: '8 hours, second shooter, engagement session included.',
    createdAt: '2026-01-25T00:00:00.000Z',
  },
  {
    id: 'vendor-golden-hour',
    weddingId: DEMO_WEDDING_ID,
    name: 'Golden Hour Studio',
    category: 'photography',
    status: 'contacted',
    budgetCategoryId: CATEGORY.photography,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '5200',
    notes: null,
    createdAt: '2026-01-22T00:00:00.000Z',
  },
  {
    id: 'vendor-twin-lens',
    weddingId: DEMO_WEDDING_ID,
    name: 'Twin Lens Collective',
    category: 'videography',
    status: 'researching',
    budgetCategoryId: CATEGORY.videography,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '3000',
    notes: null,
    createdAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: 'vendor-northbound',
    weddingId: DEMO_WEDDING_ID,
    name: 'Northbound Films',
    category: 'videography',
    status: 'quote_received',
    budgetCategoryId: CATEGORY.videography,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '2600',
    notes: null,
    createdAt: '2026-02-03T00:00:00.000Z',
  },
  {
    id: 'vendor-ivy-bramble',
    weddingId: DEMO_WEDDING_ID,
    name: 'Ivy & Bramble Florals',
    category: 'florist',
    status: 'booked',
    budgetCategoryId: CATEGORY.florist,
    contactName: 'Rosa Delgado',
    email: null,
    phone: null,
    website: null,
    estimatedCost: '2050',
    notes: null,
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'vendor-petal-pine',
    weddingId: DEMO_WEDDING_ID,
    name: 'Petal & Pine',
    category: 'florist',
    status: 'researching',
    budgetCategoryId: CATEGORY.florist,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '1900',
    notes: null,
    createdAt: '2026-02-28T00:00:00.000Z',
  },
  {
    id: 'vendor-night-sky',
    weddingId: DEMO_WEDDING_ID,
    name: 'The Night Sky Trio',
    category: 'music',
    status: 'contacted',
    budgetCategoryId: CATEGORY.music,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '2200',
    notes: null,
    createdAt: '2026-02-05T00:00:00.000Z',
  },
  {
    id: 'vendor-dj-marlowe',
    weddingId: DEMO_WEDDING_ID,
    name: 'DJ Marlowe',
    category: 'music',
    status: 'quote_received',
    budgetCategoryId: CATEGORY.music,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '1800',
    notes: null,
    createdAt: '2026-02-06T00:00:00.000Z',
  },
  {
    id: 'vendor-bloom-brush',
    weddingId: DEMO_WEDDING_ID,
    name: 'Bloom & Brush Beauty',
    category: 'beauty',
    status: 'booked',
    budgetCategoryId: CATEGORY.beauty,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '850',
    notes: null,
    createdAt: '2026-03-10T00:00:00.000Z',
  },
  {
    id: 'vendor-chapelwood',
    weddingId: DEMO_WEDDING_ID,
    name: 'Chapelwood Rentals',
    category: 'rentals',
    status: 'contacted',
    budgetCategoryId: CATEGORY.rentals,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '1500',
    notes: null,
    createdAt: '2026-02-20T00:00:00.000Z',
  },
  {
    id: 'vendor-fireside',
    weddingId: DEMO_WEDDING_ID,
    name: 'Fireside Tent & Table',
    category: 'rentals',
    status: 'declined',
    budgetCategoryId: CATEGORY.rentals,
    contactName: null,
    email: null,
    phone: null,
    website: null,
    estimatedCost: '1950',
    notes: null,
    createdAt: '2026-02-18T00:00:00.000Z',
  },
];

// Committed/paid amounts below mirror what a booked vendor's contract +
// payments would roll up to server-side (see budget.service.ts) — there's
// no separate contracts/payments concept in the demo, just these numbers
// baked in directly, consistent with each booked vendor's estimatedCost
// above and a plausible partial-deposit-paid state.
export const DEMO_BUDGET_SUMMARY: BudgetSummary = {
  categories: [
    { id: CATEGORY.venue, weddingId: DEMO_WEDDING_ID, name: 'Venue', plannedAmount: '15000', sortOrder: 0, committedAmount: '14200', paidAmount: '3550' },
    { id: CATEGORY.catering, weddingId: DEMO_WEDDING_ID, name: 'Catering', plannedAmount: '8000', sortOrder: 1, committedAmount: '7600', paidAmount: '1900' },
    { id: CATEGORY.photography, weddingId: DEMO_WEDDING_ID, name: 'Photography', plannedAmount: '4500', sortOrder: 2, committedAmount: '4300', paidAmount: '1075' },
    { id: CATEGORY.videography, weddingId: DEMO_WEDDING_ID, name: 'Videography', plannedAmount: '2800', sortOrder: 3, committedAmount: '0', paidAmount: '0' },
    { id: CATEGORY.florist, weddingId: DEMO_WEDDING_ID, name: 'Florist', plannedAmount: '2200', sortOrder: 4, committedAmount: '2050', paidAmount: '500' },
    { id: CATEGORY.music, weddingId: DEMO_WEDDING_ID, name: 'Music', plannedAmount: '2500', sortOrder: 5, committedAmount: '0', paidAmount: '0' },
    { id: CATEGORY.beauty, weddingId: DEMO_WEDDING_ID, name: 'Beauty', plannedAmount: '900', sortOrder: 6, committedAmount: '850', paidAmount: '200' },
    { id: CATEGORY.rentals, weddingId: DEMO_WEDDING_ID, name: 'Rentals', plannedAmount: '1600', sortOrder: 7, committedAmount: '0', paidAmount: '0' },
  ],
  uncategorized: { committedAmount: '0', paidAmount: '0' },
  totals: { plannedAmount: '37500', committedAmount: '29000', paidAmount: '7225' },
};

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-save-the-dates',
    weddingId: DEMO_WEDDING_ID,
    title: 'Send save-the-dates',
    description: null,
    status: 'done',
    dueDate: null,
    assigneeMemberId: null,
    assigneeLabel: 'Priya',
    vendorId: null,
    category: null,
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'task-venue-walkthrough',
    weddingId: DEMO_WEDDING_ID,
    title: 'Book venue walkthrough',
    description: null,
    status: 'done',
    dueDate: null,
    assigneeMemberId: null,
    assigneeLabel: 'Sam',
    vendorId: null,
    category: null,
    createdAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'task-headcount',
    weddingId: DEMO_WEDDING_ID,
    title: 'Confirm final headcount with caterer',
    description: null,
    status: 'in_progress',
    dueDate: daysFromNow(12),
    assigneeMemberId: null,
    assigneeLabel: 'Priya',
    vendorId: 'vendor-saffron',
    category: null,
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'task-dress-fitting',
    weddingId: DEMO_WEDDING_ID,
    title: 'Schedule dress fitting',
    description: null,
    status: 'in_progress',
    dueDate: daysFromNow(9),
    assigneeMemberId: null,
    assigneeLabel: 'Priya',
    vendorId: null,
    category: null,
    createdAt: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'task-hair-makeup-trial',
    weddingId: DEMO_WEDDING_ID,
    title: 'Book hair & makeup trial',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(-5), // deliberately overdue — shows the "Due" highlight
    assigneeMemberId: null,
    assigneeLabel: 'Priya',
    vendorId: 'vendor-bloom-brush',
    category: null,
    createdAt: '2026-03-10T00:00:00.000Z',
  },
  {
    id: 'task-seating-chart',
    weddingId: DEMO_WEDDING_ID,
    title: 'Finalize seating chart',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(21),
    assigneeMemberId: null,
    assigneeLabel: 'Sam',
    vendorId: null,
    category: null,
    createdAt: '2026-03-12T00:00:00.000Z',
  },
  {
    id: 'task-wedding-bands',
    weddingId: DEMO_WEDDING_ID,
    title: 'Order wedding bands',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(35),
    assigneeMemberId: null,
    assigneeLabel: null,
    vendorId: null,
    category: null,
    createdAt: '2026-03-14T00:00:00.000Z',
  },
  {
    id: 'task-mail-invitations',
    weddingId: DEMO_WEDDING_ID,
    title: 'Mail invitations',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(18),
    assigneeMemberId: null,
    assigneeLabel: 'Priya',
    vendorId: null,
    category: null,
    createdAt: '2026-03-16T00:00:00.000Z',
  },
  {
    id: 'task-ceremony-readings',
    weddingId: DEMO_WEDDING_ID,
    title: 'Choose ceremony readings',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(28),
    assigneeMemberId: null,
    assigneeLabel: null,
    vendorId: null,
    category: null,
    createdAt: '2026-03-18T00:00:00.000Z',
  },
  {
    id: 'task-venue-balance',
    weddingId: DEMO_WEDDING_ID,
    title: 'Confirm final balance due date with venue',
    description: null,
    status: 'todo',
    dueDate: daysFromNow(60),
    assigneeMemberId: null,
    assigneeLabel: null,
    vendorId: 'vendor-willowmere',
    category: null,
    createdAt: '2026-03-20T00:00:00.000Z',
  },
];
